site.host=
render.index=true
render.sitemap=true
render.feed=false
render.archive=false
render.tags=false
template.index.file=index.thyme
template.page.file=page.thyme
template.feed.file=feed.thyme
template.sitemap.file=sitemap.thyme
